version: "3.8"

services:
  database:
    image: mysql
    container_name: EnergyPilot_Database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  api:
    container_name: EnergyPilot_Backend
    image: energy_pilot_backend
    build: .
    command: bash -c 'while !</dev/tcp/database/3306; do sleep 3; done; npm run start'
    environment:
      - DB_HOST=database
    ports:
      - "8000:8000"
    depends_on:
      - database

  nginx:
    image: nginx
    container_name: EnergyPilot_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/certs/:/etc/nginx/certs/
    depends_on:
      - database
      - api

volumes:
  dbdata:

