name: Tests

on: [push, pull_request]

env:
  SSL_KEY: ${{ secrets.SSL_KEY }}
  SSL_CERT: ${{ secrets.SSL_CERT }}
  JWT_SECRET_TOKEN: ${{ secrets.JWT_SECRET_TOKEN }}
  PUBLIC_SALT: ${{ secrets.PUBLIC_SALT }}


jobs:
  build:

    runs-on: ubuntu-latest

    environment: test


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19

    - name: Install dependencies
      run: npm i

    - name: Run the tests
      run: npm test -- --coverage