name: Deploy

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

env:
  SSL_KEY: ${{ secrets.SSL_KEY }}
  SSL_CERT: ${{ secrets.SSL_CERT }}
  JWT_SECRET_TOKEN: ${{ secrets.JWT_SECRET_TOKEN }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}


jobs:
  build:

    runs-on: [self-hosted, prod]

    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create .env file
      run : |
        echo "DB_HOST=${{ env.DB_HOST }}" > .env
        echo "DB_USER=${{ env.DB_USER }}" >> .env
        echo "DB_SCHEMA=${{ env.DB_SCHEMA }}" >> .env
        echo "DB_PORT=${{ env.DB_PORT }}" >> .env
        echo "PUBLIC_SALT=${{ env.PUBLIC_SALT }}" >> .env
        echo "SSL_KEY=${{ env.SSL_KEY }}" >> .env
        echo "SSL_CERT=${{ env.SSL_CERT }}" >> .env
        echo "JWT_SECRET_TOKEN=${{ env.JWT_SECRET_TOKEN }}" >> .env
        echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env
        echo "DB_ROOT_PASSWORD=${{ env.DB_ROOT_PASSWORD }}" >> .env

    - name: Build and start container
      run: sudo docker-compose up --build
